// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Runtime.Serialization;
using FuzzyLogic;

namespace FuzzyLogic
{
	[DataContract]
	public class Antecedent : Object
	{
		[DataMember(Name="Expression")]
		private int ExpressionByID { get; set; }
		[IgnoreDataMember]
		public Expression Expression {
			get { return (Expression) Referee.internals [ExpressionByID]; }
			set { ExpressionByID = value.ID; }
		}
		//
		public override string ToString ()
		{
			return Expression.ToString ();
		}
	}
}
