// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using FuzzyLogic;

namespace FuzzyLogic
{
	[DataContract]
	public class Consequent : Object
	{
		[DataMember(Name="Conclusions")]
		public List < int > ConclusionsByID { get; set; }
		[IgnoreDataMember]
		public IndirectObjectList<Proposition> Conclusions {
			get { 
				if (ConclusionsByID == null)
					ConclusionsByID = new List < int > ();
				return new IndirectObjectList<Proposition> (this.Referee, ConclusionsByID);
			}
		}

		public Proposition this [int index]
		{
			get {
				if ((index >= 0) && (index < Conclusions.Count))
					return (Proposition) Referee.internals [ConclusionsByID [index]];
				else throw new IndexOutOfRangeException();
			}
		}
		public int Count {
			get { return Conclusions.Count; }
		}
		public void Add ( Proposition conclusion )
		{
			if ( ConclusionsByID == null )
				ConclusionsByID = new List < int > ();
			ConclusionsByID.Add (conclusion.ID);
		}
		//
		public override string ToString ()
		{
			string result = "";
			foreach ( Proposition prop in Conclusions ) {
				if ( result != "" ) result += " and ";
				result += prop.ToString ();
			}
			return result;
		}
	}
}

