// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Runtime.Serialization;
using FuzzyLogic;

namespace FuzzyLogic
{
	[DataContract]
	public class Operator : Expression
	{
		[DataMember(Name="OperatorName")]
		public string OperatorName { get; set; }
		[DataMember(Name="Left")]
		private int LeftByID;
		[DataMember(Name="Term")]
		private int RightByID;
		[IgnoreDataMember]
		public Expression Left {
			get { return (Expression) Referee.internals [LeftByID]; }
			set { LeftByID = value.ID; }
		}
		[IgnoreDataMember]
		public Expression Right {
			get { return (Expression) Referee.internals [RightByID]; }
			set { RightByID = value.ID; }
		}
	}
}
