// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Runtime.Serialization;
using FuzzyLogic;

namespace FuzzyLogic
{
	// TODO: Add Hedges support
	[DataContract]
	public class Proposition : Expression
	{
		[DataMember(Name="Variable")]
		private int VariableByID;
		[DataMember(Name="Term")]
		private int TermByID;
		[IgnoreDataMember]
		public Variable Variable {
			get { return (Variable) Referee.internals [VariableByID]; }
			set { VariableByID = value.ID; }
		}
		[IgnoreDataMember]
		public Curve Term {
			get { return (Curve) Referee.internals [TermByID]; }
			set { TermByID = value.ID; }
		}
		//
		public override string ToString ()
		{
			return Variable.Name + " is " + Term.Name;
		}
	}
}
