// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Runtime.Serialization;
using FuzzyLogic;

namespace FuzzyLogic
{
	// TODO: Add Hedges support
	[DataContract]
	public class Rule : Object
	{
		[DataMember(Name="Weight")]
		public float Weight { get; set; }
		[DataMember(Name="Antecedent")]
		private int AntecedentByID;
		[DataMember(Name="Consequent")]
		private int ConsequentByID;
		[IgnoreDataMember]
		public Antecedent Antecedent {
			get { return (Antecedent) Referee.internals [AntecedentByID]; }
			set { AntecedentByID = value.ID; }
		}
		[IgnoreDataMember]
		public Consequent Consequent {
			get { return (Consequent) Referee.internals [ConsequentByID]; }
			set { ConsequentByID = value.ID; }
		}
		public override string ToString ()
		{
			return "if " + Antecedent + " then " + Consequent;
		}
	}
}
