// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

using Conjunction = FuzzyLogicSolver.TNorm;
using Disjunction = FuzzyLogicSolver.SNorm;
using Activation = FuzzyLogicSolver.TNorm;
using Accumulation = FuzzyLogicSolver.SNorm;
using Defuzzyfier = FuzzyLogicSolver.Defuzzyfier;

namespace FuzzyLogicSolver
{
	public class Activated
	{
		Curve term;
		float degree;
		Activation activation;
		public Activated (Curve t, float deg,Activation act)
		{
			term = t;
			degree = deg;
			activation = act;
		}
		//
		public Curve Term {
			get { return term; }
		}
		public float Degree {
			get { return degree; }
		}
		public Activation Activation {
			get { return activation; }
		}
		//
		public float Membership (float value)
		{
			return activation.Compute(term.Membership(value),degree);
		}
	}
}
