// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace FuzzyLogicSolver
{
	[System.Serializable]
	public abstract class Defuzzyfier : Object
	{
		protected Defuzzyfier ()
		{
		}
		public abstract float defuzzify ( Accumulated term, float minimum, float maximum );
	}
}
