// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

using FuzzyLogic;

namespace FuzzyLogicSolver
{
	public abstract class Norm : Object
	{
		protected Norm ()
		{
		}
		public abstract float Compute ( float a,float b );
	}
}

