// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Runtime.Serialization;

namespace FuzzyLogic
{
	[DataContract]
	public class NamedObject : Object
	{
		[DataMember(Name="Name")]
		public string Name { get; set; }
	}
}

