// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Runtime.Serialization;

using DesignPatterns;

namespace FuzzyLogic
{
	[KnownType(typeof(Object))]
	[KnownType(typeof(NamedObject))]
	[KnownType(typeof(Variable))]
	[KnownType(typeof(InputVariable))]
	[KnownType(typeof(OutputVariable))]
	[KnownType(typeof(Keyframe))]
	[KnownType(typeof(Curve))]
	[KnownType(typeof(Antecedent))]
	[KnownType(typeof(Consequent))]
	[KnownType(typeof(Expression))]
	[KnownType(typeof(Operator))]
	[KnownType(typeof(Proposition))]
	[KnownType(typeof(Rule))]
	[KnownType(typeof(RuleBlock))]
	[DataContract]
	public class Object : INamedClass
	{
		[DataMember(Name="Id")]
		public int ID { get; internal set; }
		[DataMember(Name="ClassName")]
		public string ClassName { get; set; }
		[IgnoreDataMember]
		internal Engine Referee { get; set; }

		public Object ()
		{
			string tmp = GetType().Name;
			ClassName = tmp;
			ID = currentID++;
		}
		public static implicit operator int(Object d)
		{
			return d.ID;
		}
		public static int currentID = 0;
	}
}

