// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Runtime.Serialization;

using FuzzyLogic;

namespace FuzzyLogic
{
	[DataContract]
	public sealed class InputVariable : Variable
	{
		[DataMember(Name="Value")]
		public float Value { get; set; }
	}
}

