// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Runtime.Serialization;

using FuzzyLogic;

namespace FuzzyLogic
{
	[DataContract]
	public class Variable : NamedObject
	{
		[DataMember]
		public float Minimum { get; set; }
		[DataMember]
		public float Maximum { get; set; }
		[DataMember(Name="Terms")]
		private List < int > TermsByID { get; set; }
		[IgnoreDataMember]
		public IndirectObjectList<Curve> Terms {
			get {
				if (TermsByID == null)
					TermsByID = new List < int > ();
				return new IndirectObjectList<Curve> (this.Referee,TermsByID);
			}
		}

		public Curve this [int index]
		{
			get {
				if ( ( index >= 0 ) && ( index < TermsByID.Count ) )
					return (Curve) Referee.internals [ TermsByID [ index ] ];
				else throw new IndexOutOfRangeException();
			}
		}
		public Curve this [string nm] {
			get {
				for (int i = 0; i < Terms.Count; i++) {
					NamedObject obj = (NamedObject)Referee.internals [TermsByID [i]];
					if (obj.Name == nm)
						return (Curve) obj;
				}
				throw new IndexOutOfRangeException();
			}
		}

		public void Add ( Curve set )
		{
			if (TermsByID == null)
				TermsByID = new List < int > ();
			TermsByID.Add (set);
		}
	}
}
